##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
cron_path: "/var/spool/cron"

packages:
  - openstack-keystone

services:
  - httpd

apache_config_dir: /etc/httpd/conf.d
http_service_name: httpd
